version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/creditcard-comparor
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 120000
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 120000
      runas: root
